mock:
  domain: jq.server.com
  user-account:
    account: user
    password: 123
    nickname: 张三
    friends: ["李四", "王五"]
  registerClient:
    client-123: pwd-123
spring:
  thymeleaf:
    cache: false
jwt:
  secret: iskrc8#-xsi7d0-21n389asndj1LJHUGH*290BIWe9j213knmohs7
  patterns:
    - "/resource/**"
    - "/user/**"
